version: '3.4'

services:
  probot:
    image: safe-settings
    build: .
    environment:
      NODE_ENV: production
      APP_ID: ${APP_ID}
      GH_ORG: ${GH_ORG}
      WEBHOOK_PROXY_URL: ${WEBHOOK_PROXY_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DEPLOYMENT_CONFIG_FILE: ${DEPLOYMENT_CONFIG_FILE}
      LOG_LEVEL: ${LOG_LEVEL}
      ENABLE_PR_COMMENT: ${ENABLE_PR_COMMENT}
      SENTRY_DSN: ${SENTRY_DSN}
    ports:
      - 3001:3000
    volumes:
      - type: bind
        source: ./deployment-settings.yml
        target: /opt/safe-settings/deployment-settings.yml
        read_only: true
